# Generated by Django 5.1.3 on 2024-11-14 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('parque', 'Parque'), ('auditorio', 'Auditorio'), ('salon', 'Salón'), ('campo', 'Campo')], max_length=50, unique=True, verbose_name='Tipo de Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], default='disponible', max_length=20)),
                ('tipo_espacio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='espacios', to='lugares.tipolugar')),
            ],
        ),
    ]
